In [3]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: (x*2)+10, items))
squared

[12, 14, 16, 18, 20]

In [4]:
items1 = [1, 2, 3, 4, 5]
items2 = [6, 7, 8, 9, 10]
squared = list(map(lambda x,y: x+y, items1,items2))
squared

[7, 9, 11, 13, 15]

In [7]:
import numpy 
var1 = numpy.array([1, 2, 3, 4, 5])
(var1*2)+10

array([12, 14, 16, 18, 20])

In [8]:
np_2d= np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, "68.7"]])
np_2d[:,1:3]

array([['1.68', '1.71'],
       ['59.2', '63.6']], dtype='<U32')

In [14]:
print(np_2d)
np_2d > 50.0

[['1.73' '1.68' '1.71' '1.89' '1.79']
 ['65.4' '59.2' '63.6' '88.4' '68.7']]


TypeError: unorderable types: numpy.ndarray() > float()

In [22]:
x2 = np.random.randint(10, size=(3, 4))


In [23]:
x2

array([[4, 3, 0, 3],
       [5, 0, 2, 3],
       [8, 1, 3, 3]])

In [24]:
x2[:2,1:3]

array([[3, 0],
       [0, 2]])

In [1]:
import numpy as np
np.random.seed(0)