In [1]:
import numpy as np

In [2]:
var1 = np.array([1,2,3])
items = [1, 2, 3, 4, 5]

In [3]:
print(var1)
print(type(items))
print(type(var1))

[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
var2 = np.array([[1,2,3],[4,5,6]])

In [5]:
print(var2)
print(var2.shape)
print(var1.shape)
print(np.shape(var1))

[[1 2 3]
 [4 5 6]]
(2, 3)
(3,)
(3,)


In [6]:
print(var2.dtype)
print(var2.ndim)
print(var1.ndim)
var2[0,1]


int64
2
1


2

In [7]:
x = np.arange(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [13]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
np.full((3,3),1.0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.diag([3,3,2])

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 2]])

In [19]:
v = np.array([1,2])
v

array([1, 2])

In [20]:
np.tile(v,(3,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [21]:
np.random.random()

0.1256149346882819

In [22]:
np.random.random((3,2))

array([[0.83374017, 0.26939005],
       [0.11129223, 0.39297283],
       [0.80102657, 0.58765858]])